// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjwmegdklymvroznpjgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqd21lZ2RrbHltdnJvem5wamdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDMzOTcsImV4cCI6MjA2MDQ3OTM5N30.BD6OhOOjmcH_ZHvYVygMWNZzMf2tp8rcEz1GP3japTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);